class decoding{
    public static void main(String[] args){
        String s="Khoor! L zrxog uhdoob olnh wr jlyh brx d jliw iru Fkulvwpdv. L nqrz brx olnh jdphv, vr khuh lv d vwhdp jliw fdug frgh wr hqmrb vrph iuhh wlph eb brxuvhoi: UOJUG-W8ZTG-IFCEA Brx duh dpdclqj! Frqjudwv! Brx khoshg Fdhvdu dqg kh lv qrz pduulhg! ^^ Ohdylqj Fdhvdu zlwk klv kdssb zlih ehklqg, L uhdoob wklqn brx pljkw eh dq lqwhuhvwlqj shuvrq, exw L qhyhu dfwxdoob jrw wkh fkdqfh wr wdon wr brx pruh shuvrqdoob, rq d ghhshu ohyho. L nqrz. Zh duh froohdjxhv dqg wklv vrxqgv olnh Fkulvwpdv ev, exw L uhdoob wklqn d vhqvh ri frppxqlwb lv zkdw'v jrlqj wr nhhs ph vdqh gxulqj wkhvh 4 bhduv :). Pdbeh brx, ph, Lrqxw, Dqguhl, Wlqd, Ulfkdug zkrhyhu brx pljkw olnh, fdq rujdqlvh d gdb rxw lq wkh sdun ru d vwxgb vhvvlrq (vlqfh wkh hadpv duh frplqj). L wklqn wkdw zrxog eh ixq dqg zh pljkw jhw wkh fkdqfh wr nqrz hdfk rwkhu ehwwhu (dqg pdbeh sodb zlwk wkhvh frro elfbfoh fdugv L mxvw jdyh brx) Ohw ph nqrz li brx vroyhg wkh sxccoh rq zkdwvdss dqg krz gliilfxow lw zdv ;) Kdssb krolgdbv!";
        s=s.replaceAll("a","x");
        s=s.replaceAll("A","X");
        s=s.replaceAll("L","I");
        s=s.replaceAll("e","b");
        s=s.replaceAll("E","B");
        s=s.replaceAll("w","t");
        s=s.replaceAll("W","T");
        s=s.replaceAll("z","w");
        s=s.replaceAll("Z","W");
        s=s.replaceAll("c","z");
        s=s.replaceAll("C","Z");
        s=s.replaceAll("f","c");
        s=s.replaceAll("F","C");
        s=s.replaceAll("i","f");
        //s=s.replaceAll("I","F");
        s=s.replaceAll("d","a");
        s=s.replaceAll("D","A");
        s=s.replaceAll("l","i");
        s=s.replaceAll("o","l");
        s=s.replaceAll("O","L");
        s=s.replaceAll("h","e");
        s=s.replaceAll("k","h");
        s=s.replaceAll("K","H");
        s=s.replaceAll("r","o");
        s=s.replaceAll("u","r");
        s=s.replaceAll("U","R");
        s=s.replaceAll("g","d");
        s=s.replaceAll("G","D");
        s=s.replaceAll("x","u");
        s=s.replaceAll("j","g");
        s=s.replaceAll("J","G");
        s=s.replaceAll("m","j");
        s=s.replaceAll("p","m");
        s=s.replaceAll("P","M");
        s=s.replaceAll("s","p");
        s=s.replaceAll("v","s");
        s=s.replaceAll("y","v");
        s=s.replaceAll("b","y");
        s=s.replaceAll("B","Y");
        s=s.replaceAll("k","h");
        s=s.replaceAll("n","k");
        s=s.replaceAll("q","n");
        System.out.println(s);
    }
}